import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "../components/Navbar";
import Main from "./Main";
import { BsChatLeftTextFill } from "react-icons/bs";

export default function Home() {
  const router = useRouter();
  const toMail = () => {
    router.push(
      "mailto:roziqinkhoeru8@gmail.com?subject=Collaboration%20Request"
    );
  };
  return (
    <div className='relative'>
      <Head>
        <title>Khoeru Roziqin</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <Main />
      <div className='fixed right-6 sm:right-12 bottom-6 sm:bottom-8'>
        <button
          onClick={() => toMail()}
          className='flex justify-center items-center bg-slate-600 hover:bg-slate-500 w-14 h-14 rounded-full'
        >
          <BsChatLeftTextFill size={24} />
        </button>
      </div>
    </div>
  );
}
