import Head from "next/head";
import Main from "./Main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Khoeru Roziqin</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Main />
    </div>
  );
}
